# Generated by Django 3.2.9 on 2021-12-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Anunciante', 'Anunciante')], default='Anunciante', max_length=100),
        ),
    ]
