# Generated by Django 3.2.9 on 2021-12-05 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=255)),
                ('descricao_peca', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('info_contato', models.CharField(max_length=255)),
                ('status_finalizacao', models.BooleanField(default=False)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
